In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [19]:
cars = pd.read_csv("Car details.csv")
cars.head(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0

In [21]:
lumn = cars['torque']
lumn.head(3)

0           190Nm@ 2000rpm
1      250Nm@ 1500-2500rpm
2    12.7@ 2,700(kgm@ rpm)
Name: torque, dtype: object

In [23]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [25]:
cars.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [27]:
cars.shape

(8128, 13)

In [29]:
cars.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [31]:
cars = cars.dropna()

In [33]:
cars.shape

(7906, 13)

In [35]:
import re

In [37]:
# Function to clean and extract torque and RPM
def extract_torque_rpm(torque_str):
    if not torque_str or pd.isna(torque_str):
        return None, None  # Handle empty or NaN values

    # Step 1: Standardize string: remove spaces and commas, convert to lowercase
    torque_str = torque_str.replace(" ", "").replace(",", "").lower()

    # Step 2: Extract torque value and unit (Nm or kgm)
    torque_match = re.search(r'([\d\.]+)(nm|kgm)?', torque_str)
    if torque_match:
        torque_value = float(torque_match.group(1))
        torque_unit = torque_match.group(2)

        # Convert kgm to Nm (1 kgm ≈ 9.80665 Nm)
        if torque_unit == 'kgm':
            torque_value *= 9.80665
    else:
        torque_value = None

    # Step 3: Extract RPM value(s)
    rpm_match = re.search(r'(\d+)(?:-)?(\d+)?rpm', torque_str)
    if rpm_match:
        # If it's a range like 1750-2750, take the lower bound
        rpm_value = int(rpm_match.group(1))
    else:
        rpm_value = None

    return torque_value, rpm_value

torque_list = cars['torque'].to_list()  # Extracting the 'torque' column as a list

# Apply the function to each item in the torque_list using list comprehension
results = [extract_torque_rpm(torque) for torque in torque_list]

# Convert the result into two separate lists: torque_nm and torque_rpm
torque_nm, torque_rpm = zip(*results)

# Add the two lists as new columns in the original DataFrame
cars['torque_nm'] = torque_nm
cars['torque_rpm'] = torque_rpm

# Display the DataFrame with new columns
#print(cars)

In [39]:
cars.head(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,torque_nm,torque_rpm
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.0,2000.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,250.0,1500.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,12.7,NaN

In [41]:
cars.head(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,torque_nm,torque_rpm
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.0,2000.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,250.0,1500.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,12.7,NaN

In [43]:
cars.describe()

,year,selling_price,km_driven,seats,torque_nm,torque_rpm
count,7906.000000,7.906000e+03,7.906000e+03,7906.000000,7906.000000,7462.000000
mean,2013.983936,6.498137e+05,6.918866e+04,5.416393,170.341192,2704.245645
std,3.863695,8.135827e+05,5.679230e+04,0.959208,95.885066,1127.879617
min,1994.000000,2.999900e+04,1.000000e+00,2.000000,5.700000,175.000000
25%,2012.000000,2.700000e+05,3.500000e+04,5.000000,106.500000,1750.000000
50%,2015.000000,4.500000e+05,6.000000e+04,5.000000,160.000000,2000.000000
75%,2017.000000,6.900000e+05,9.542500e+04,5.000000,205.000000,4000.000000
max,2020.000000,1.000000e+07,2.360457e+06,14.000000,789.000000,5000.000000

In [73]:
# Function to extract mileage value and convert units if necessary
def extract_mileage_kmpl(mileage_str):
    if not mileage_str or pd.isna(mileage_str):
        return None  # Handle empty or NaN values
    
    # Step 1: Extract numeric value
    mileage_match = re.search(r'([\d\.]+)', mileage_str)
    if mileage_match:
        mileage_value = float(mileage_match.group(1))
    else:
        mileage_value = None
    
    # Step 2: Check the unit and convert if necessary
    if 'km/kg' in mileage_str:
        # Conversion factor from km/kg to kmpl (CNG/LPG to petrol equivalent)
        conversion_factor = 1.4  # This is an approximate value, adjust if necessary
        mileage_value *= conversion_factor
    
    return mileage_value

# Outside the function
mileage_list = cars['mileage'].to_list()  # Convert the 'mileage' column to a list
results = [extract_mileage_kmpl(miles) for miles in mileage_list]  # Apply the function to each item in the list

# Adding the results to a new column in the cars DataFrame
cars['mileage_kmpl'] = results

In [75]:
cars.shape

(7906, 16)

In [79]:
cars.head(50)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,torque_nm,torque_rpm,mileage_kmpl
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,23.400
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,250.000000,1500.0,21.140
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,12.700000,NaN,17.700
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,219.668960,1750.0,23.000
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,11.500000,NaN,16.100
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0,113.750000,4000.0,20.140
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0,7.800000,NaN,24.220
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0,59.000000,2500.0,16.100
8,Toyota Etios VXD,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59 kmpl,1364 CC,67.1 bhp,170Nm@ 1800-2400rpm,5.0,170.000000,1800.0,23.590
9,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.0 kmpl,1399 CC,68.1 bhp,160Nm@ 2000rpm,5.0,160.000000,2000.0,20.000
10,Renault Duster 110PS Diesel RxL,2014,500000,68000,Diesel,Individual,Manual,Second Owner,19.01 kmpl,1461 CC,108.45 bhp,248Nm@ 2250rpm,5.0,248.000000,2250.0,19.010
11,Maruti Zen LX,2005,92000,100000,Petrol,Individual,Manual,Second Owner,17.3 kmpl,993 CC,60 bhp,78Nm@ 4500rpm,5.0,78.000000,4500.0,17.300
12,Maruti Swift Dzire VDi,2009,280000,140000,Diesel,Individual,Manual,Second Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,19.300
14,Maruti Wagon R LXI Minor,2009,180000,90000,Petrol,Individual,Manual,Second Owner,18.9 kmpl,1061 CC,67 bhp,84Nm@ 3500rpm,5.0,84.000000,3500.0,18.900
15,Mahindra KUV 100 mFALCON G80 K8 5str,2016,400000,40000,Petrol,Individual,Manual,First Owner,18.15 kmpl,1198 CC,82 bhp,115Nm@ 3500-3600rpm,5.0,115.000000,3500.0,18.150
16,Maruti Ertiga SHVS VDI,2016,778000,70000,Diesel,Individual,Manual,Second Owner,24.52 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,7.0,200.000000,1750.0,24.520
17,Hyundai i20 1.4 CRDi Asta,2012,500000,53000,Diesel,Individual,Manual,Second Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,219.668960,1750.0,23.000
18,Maruti Alto LX,2002,150000,80000,Petrol,Individual,Manual,Second Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,62.000000,3000.0,19.700
19,Hyundai i20 2015-2017 Asta 1.4 CRDi,2016,680000,100000,Diesel,Individual,Manual,First Owner,22.54 kmpl,1396 CC,88.73 bhp,219.7Nm@ 1500-2750rpm,5.0,219.700000,1500.0,22.540
20,Mahindra Verito 1.5 D4 BSIII,2011,174000,100000,Diesel,Individual,Manual,Second Owner,21.0 kmpl,1461 CC,64.1 bhp,160Nm@ 2000rpm,5.0,160.000000,2000.0,21.000
21,Honda WR-V i-DTEC VX,2017,950000,50000,Diesel,Individual,Manual,First Owner,25.5 kmpl,1498 CC,98.6 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,25.500
22,Maruti Swift Dzire ZDI,2015,525000,40000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,26.590
23,Maruti SX4 ZDI,2012,600000,72000,Diesel,Individual,Manual,First Owner,21.5 kmpl,1248 CC,88.8 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,21.500
24,Tata Tigor 2017-2020 XZ,2018,500000,35000,Petrol,Individual,Manual,First Owner,20.3 kmpl,1199 CC,83.81 bhp,114Nm@ 3500rpm,5.0,114.000000,3500.0,20.300
25,Maruti Baleno Delta 1.2,2016,575000,45000,Petrol,Individual,Manual,First Owner,21.4 kmpl,1197 CC,83.1 bhp,115Nm@ 4000rpm,5.0,115.000000,4000.0,21.400
26,Maruti Alto 800 LXI,2017,275000,28000,Petrol,Individual,Manual,First Owner,24.7 kmpl,796 CC,47.3 bhp,69Nm@ 3500rpm,5.0,69.000000,3500.0,24.700
27,Chevrolet Enjoy TCDi LTZ 7 Seater,2013,300000,70000,Diesel,Individual,Manual,First Owner,18.2 kmpl,1248 CC,73.8 bhp,172.5Nm@ 1750rpm,7.0,172.500000,1750.0,18.200
28,Maruti Wagon R LXI Minor,2009,220000,120000,Petrol,Individual,Manual,First Owner,18.9 kmpl,1061 CC,67 bhp,84Nm@ 3500rpm,5.0,84.000000,3500.0,18.900
29,Maruti Omni E MPI STD BS IV,2018,254999,25000,Petrol,Individual,Manual,First Owner,16.8 kmpl,796 CC,34.2 bhp,59Nm@ 2500rpm,8.0,59.000000,2500.0,16.800
30,Maruti Vitara Brezza LDi Option,2017,670000,70000,Diesel,Individual,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300
32,Maruti Omni 8 Seater BSIV,2012,150000,35000,Petrol,Individual,Manual,Second Owner,14.0 kmpl,796 CC,35 bhp,6.1kgm@ 3000rpm,5.0,59.820565,3000.0,14.000
33,Hyundai i20 1.2 Asta Dual Tone,2018,730000,2388,Petrol,Individual,Manual,First Owner,18.6 kmpl,1197 CC,81.83 bhp,114.7Nm@ 4000rpm,5.0,114.700000,4000.0,18.600
34,Maruti Vitara Brezza LDi,2017,650000,16200,Diesel,Individual,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300
35,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44 km/kg,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0,60.000000,3500.0,46.816
36,Maruti Alto K10 VXI Airbag,2019,366000,15000,Petrol,Individual,Manual,First Owner,23.95 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,90.000000,3500.0,23.950
37,Hyundai Verna VTVT 1.6 SX Option,2019,1149000,5000,Petrol,Individual,Manual,First Owner,17.0 kmpl,1591 CC,121.3 bhp,151Nm@ 4850rpm,5.0,151.000000,4850.0,17.000
38,Datsun GO D,2016,150000,42000,Petrol,Individual,Manual,First Owner,20.63 kmpl,1198 CC,67 bhp,104Nm@ 4000rpm,5.0,104.000000,4000.0,20.630
39,Tata Safari DICOR 2.2 LX 4x2,2011,425000,60000,Diesel,Individual,Manual,Second Owner,13.93 kmpl,2179 CC,138.03 bhp,320Nm@ 1700-2700rpm,7.0,320.000000,1700.0,13.930
40,Maruti 800 Std,2012,150000,76000,Petrol,Individual,Manual,First Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0,59.000000,2500.0,16.100
41,Jeep Compass 1.4 Limited Plus BSIV,2019,2100000,5000,Petrol,Individual,Automatic,First Owner,16.0 kmpl,1368 CC,160.77 bhp,250Nm@ 1750-2500rpm,5.0,250.000000,1750.0,16.000
42,Honda City i VTEC VX,2018,925000,28900,Petrol,Dealer,Manual,First Owner,17.8 kmpl,1497 CC,117.3 bhp,145Nm@ 4600rpm,5.0,145.000000,4600.0,17.800
43,Honda City V MT,2013,425000,86300,Petrol,Dealer,Manual,First Owner,16.8 kmpl,1497 CC,116.3 bhp,146Nm@ 4800rpm,5.0,146.000000,4800.0,16.800
44,Maruti Swift Dzire VXi AT,2018,675000,23300,Petrol,Dealer,Automatic,First Owner,18.5 kmpl,1197 CC,83.14 bhp,115Nm@ 4000rpm,5.0,115.000000,4000.0,18.500
45,Maruti Vitara Brezza VDi,2018,819999,32600,Diesel,Dealer,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300
46,Maruti Alto K10 VXI,2018,390000,10300,Petrol,Dealer,Manual,First Owner,23.95 kmpl,998 CC,67.05 bhp,90Nm@ 3500rpm,5.0,90.000000,3500.0,23.950
47,Toyota Fortuner 4x4 MT,2014,1500000,77000,Diesel,Dealer,Manual,First Owner,12.55 kmpl,2982 CC,168.5 bhp,343Nm@ 1400-3400rpm,7.0,343.000000,1400.0,12.550
48,Toyota Innova 2.5 G (Diesel) 7 Seater BS IV,2013,700000,99000,Diesel,Dealer,Manual,First Owner,12.99 kmpl,2494 CC,100 bhp,200Nm@ 1400-3400rpm,7.0,200.000000,1400.0,12.990
49,Mercedes-Benz B Class B180,2014,1450000,27800,Diesel,Dealer,Automatic,Second Owner,14.8 kmpl,2143 CC,120.7 bhp,200Nm@ 1250-4000rpm,5.0,200.000000,1250.0,14.800
50,Honda Amaze S Diesel,2015,425000,49800,Diesel,Dealer,Manual,First Owner,24.7 kmpl,1498 CC,98.63 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.700
51,Mitsubishi Pajero Sport 4X4,2013,1090000,151000,Diesel,Dealer,Manual,First Owner,13.5 kmpl,2477 CC,175.56 bhp,400Nm@ 2000-2500rpm,7.0,400.000000,2000.0,13.500

In [83]:
# Split the 'max_power' column by space and take the first part (the numeric value)
cars['max_power_bhp'] = cars['max_power'].str.split(' ').str[0]

# Convert the resulting column to float (if necessary)
cars['max_power_bhp'] = pd.to_numeric(cars['max_power_bhp'], errors='coerce')

In [85]:
cars.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,torque_nm,torque_rpm,mileage_kmpl,max_power_bhp
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.00000,2000.0,23.40,74.00
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,250.00000,1500.0,21.14,103.52
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,12.70000,NaN,17.70,78.00
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,219.66896,1750.0,23.00,90.00
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,11.50000,NaN,16.10,88.20

In [89]:
cars['engine_cc'] = cars['engine'].str.split(' ').str[0]

cars['engine_cc'] = pd.to_numeric(cars['engine_cc'], errors='coerce')

In [95]:
cars.head(50)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,torque_nm,torque_rpm,mileage_kmpl,max_power_bhp,engine_cc
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,23.400,74.00,1248
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,250.000000,1500.0,21.140,103.52,1498
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,12.700000,NaN,17.700,78.00,1497
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,219.668960,1750.0,23.000,90.00,1396
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,11.500000,NaN,16.100,88.20,1298
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0,113.750000,4000.0,20.140,81.86,1197
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0,7.800000,NaN,24.220,57.50,1061
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0,59.000000,2500.0,16.100,37.00,796
8,Toyota Etios VXD,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59 kmpl,1364 CC,67.1 bhp,170Nm@ 1800-2400rpm,5.0,170.000000,1800.0,23.590,67.10,1364
9,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.0 kmpl,1399 CC,68.1 bhp,160Nm@ 2000rpm,5.0,160.000000,2000.0,20.000,68.10,1399
10,Renault Duster 110PS Diesel RxL,2014,500000,68000,Diesel,Individual,Manual,Second Owner,19.01 kmpl,1461 CC,108.45 bhp,248Nm@ 2250rpm,5.0,248.000000,2250.0,19.010,108.45,1461
11,Maruti Zen LX,2005,92000,100000,Petrol,Individual,Manual,Second Owner,17.3 kmpl,993 CC,60 bhp,78Nm@ 4500rpm,5.0,78.000000,4500.0,17.300,60.00,993
12,Maruti Swift Dzire VDi,2009,280000,140000,Diesel,Individual,Manual,Second Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,19.300,73.90,1248
14,Maruti Wagon R LXI Minor,2009,180000,90000,Petrol,Individual,Manual,Second Owner,18.9 kmpl,1061 CC,67 bhp,84Nm@ 3500rpm,5.0,84.000000,3500.0,18.900,67.00,1061
15,Mahindra KUV 100 mFALCON G80 K8 5str,2016,400000,40000,Petrol,Individual,Manual,First Owner,18.15 kmpl,1198 CC,82 bhp,115Nm@ 3500-3600rpm,5.0,115.000000,3500.0,18.150,82.00,1198
16,Maruti Ertiga SHVS VDI,2016,778000,70000,Diesel,Individual,Manual,Second Owner,24.52 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,7.0,200.000000,1750.0,24.520,88.50,1248
17,Hyundai i20 1.4 CRDi Asta,2012,500000,53000,Diesel,Individual,Manual,Second Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,219.668960,1750.0,23.000,90.00,1396
18,Maruti Alto LX,2002,150000,80000,Petrol,Individual,Manual,Second Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,62.000000,3000.0,19.700,46.30,796
19,Hyundai i20 2015-2017 Asta 1.4 CRDi,2016,680000,100000,Diesel,Individual,Manual,First Owner,22.54 kmpl,1396 CC,88.73 bhp,219.7Nm@ 1500-2750rpm,5.0,219.700000,1500.0,22.540,88.73,1396
20,Mahindra Verito 1.5 D4 BSIII,2011,174000,100000,Diesel,Individual,Manual,Second Owner,21.0 kmpl,1461 CC,64.1 bhp,160Nm@ 2000rpm,5.0,160.000000,2000.0,21.000,64.10,1461
21,Honda WR-V i-DTEC VX,2017,950000,50000,Diesel,Individual,Manual,First Owner,25.5 kmpl,1498 CC,98.6 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,25.500,98.60,1498
22,Maruti Swift Dzire ZDI,2015,525000,40000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,190.000000,2000.0,26.590,74.00,1248
23,Maruti SX4 ZDI,2012,600000,72000,Diesel,Individual,Manual,First Owner,21.5 kmpl,1248 CC,88.8 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,21.500,88.80,1248
24,Tata Tigor 2017-2020 XZ,2018,500000,35000,Petrol,Individual,Manual,First Owner,20.3 kmpl,1199 CC,83.81 bhp,114Nm@ 3500rpm,5.0,114.000000,3500.0,20.300,83.81,1199
25,Maruti Baleno Delta 1.2,2016,575000,45000,Petrol,Individual,Manual,First Owner,21.4 kmpl,1197 CC,83.1 bhp,115Nm@ 4000rpm,5.0,115.000000,4000.0,21.400,83.10,1197
26,Maruti Alto 800 LXI,2017,275000,28000,Petrol,Individual,Manual,First Owner,24.7 kmpl,796 CC,47.3 bhp,69Nm@ 3500rpm,5.0,69.000000,3500.0,24.700,47.30,796
27,Chevrolet Enjoy TCDi LTZ 7 Seater,2013,300000,70000,Diesel,Individual,Manual,First Owner,18.2 kmpl,1248 CC,73.8 bhp,172.5Nm@ 1750rpm,7.0,172.500000,1750.0,18.200,73.80,1248
28,Maruti Wagon R LXI Minor,2009,220000,120000,Petrol,Individual,Manual,First Owner,18.9 kmpl,1061 CC,67 bhp,84Nm@ 3500rpm,5.0,84.000000,3500.0,18.900,67.00,1061
29,Maruti Omni E MPI STD BS IV,2018,254999,25000,Petrol,Individual,Manual,First Owner,16.8 kmpl,796 CC,34.2 bhp,59Nm@ 2500rpm,8.0,59.000000,2500.0,16.800,34.20,796
30,Maruti Vitara Brezza LDi Option,2017,670000,70000,Diesel,Individual,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300,88.50,1248
32,Maruti Omni 8 Seater BSIV,2012,150000,35000,Petrol,Individual,Manual,Second Owner,14.0 kmpl,796 CC,35 bhp,6.1kgm@ 3000rpm,5.0,59.820565,3000.0,14.000,35.00,796
33,Hyundai i20 1.2 Asta Dual Tone,2018,730000,2388,Petrol,Individual,Manual,First Owner,18.6 kmpl,1197 CC,81.83 bhp,114.7Nm@ 4000rpm,5.0,114.700000,4000.0,18.600,81.83,1197
34,Maruti Vitara Brezza LDi,2017,650000,16200,Diesel,Individual,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300,88.50,1248
35,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44 km/kg,796 CC,40.3 bhp,60Nm@ 3500rpm,4.0,60.000000,3500.0,46.816,40.30,796
36,Maruti Alto K10 VXI Airbag,2019,366000,15000,Petrol,Individual,Manual,First Owner,23.95 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,90.000000,3500.0,23.950,67.10,998
37,Hyundai Verna VTVT 1.6 SX Option,2019,1149000,5000,Petrol,Individual,Manual,First Owner,17.0 kmpl,1591 CC,121.3 bhp,151Nm@ 4850rpm,5.0,151.000000,4850.0,17.000,121.30,1591
38,Datsun GO D,2016,150000,42000,Petrol,Individual,Manual,First Owner,20.63 kmpl,1198 CC,67 bhp,104Nm@ 4000rpm,5.0,104.000000,4000.0,20.630,67.00,1198
39,Tata Safari DICOR 2.2 LX 4x2,2011,425000,60000,Diesel,Individual,Manual,Second Owner,13.93 kmpl,2179 CC,138.03 bhp,320Nm@ 1700-2700rpm,7.0,320.000000,1700.0,13.930,138.03,2179
40,Maruti 800 Std,2012,150000,76000,Petrol,Individual,Manual,First Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0,59.000000,2500.0,16.100,37.00,796
41,Jeep Compass 1.4 Limited Plus BSIV,2019,2100000,5000,Petrol,Individual,Automatic,First Owner,16.0 kmpl,1368 CC,160.77 bhp,250Nm@ 1750-2500rpm,5.0,250.000000,1750.0,16.000,160.77,1368
42,Honda City i VTEC VX,2018,925000,28900,Petrol,Dealer,Manual,First Owner,17.8 kmpl,1497 CC,117.3 bhp,145Nm@ 4600rpm,5.0,145.000000,4600.0,17.800,117.30,1497
43,Honda City V MT,2013,425000,86300,Petrol,Dealer,Manual,First Owner,16.8 kmpl,1497 CC,116.3 bhp,146Nm@ 4800rpm,5.0,146.000000,4800.0,16.800,116.30,1497
44,Maruti Swift Dzire VXi AT,2018,675000,23300,Petrol,Dealer,Automatic,First Owner,18.5 kmpl,1197 CC,83.14 bhp,115Nm@ 4000rpm,5.0,115.000000,4000.0,18.500,83.14,1197
45,Maruti Vitara Brezza VDi,2018,819999,32600,Diesel,Dealer,Manual,First Owner,24.3 kmpl,1248 CC,88.5 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.300,88.50,1248
46,Maruti Alto K10 VXI,2018,390000,10300,Petrol,Dealer,Manual,First Owner,23.95 kmpl,998 CC,67.05 bhp,90Nm@ 3500rpm,5.0,90.000000,3500.0,23.950,67.05,998
47,Toyota Fortuner 4x4 MT,2014,1500000,77000,Diesel,Dealer,Manual,First Owner,12.55 kmpl,2982 CC,168.5 bhp,343Nm@ 1400-3400rpm,7.0,343.000000,1400.0,12.550,168.50,2982
48,Toyota Innova 2.5 G (Diesel) 7 Seater BS IV,2013,700000,99000,Diesel,Dealer,Manual,First Owner,12.99 kmpl,2494 CC,100 bhp,200Nm@ 1400-3400rpm,7.0,200.000000,1400.0,12.990,100.00,2494
49,Mercedes-Benz B Class B180,2014,1450000,27800,Diesel,Dealer,Automatic,Second Owner,14.8 kmpl,2143 CC,120.7 bhp,200Nm@ 1250-4000rpm,5.0,200.000000,1250.0,14.800,120.70,2143
50,Honda Amaze S Diesel,2015,425000,49800,Diesel,Dealer,Manual,First Owner,24.7 kmpl,1498 CC,98.63 bhp,200Nm@ 1750rpm,5.0,200.000000,1750.0,24.700,98.63,1498
51,Mitsubishi Pajero Sport 4X4,2013,1090000,151000,Diesel,Dealer,Manual,First Owner,13.5 kmpl,2477 CC,175.56 bhp,400Nm@ 2000-2500rpm,7.0,400.000000,2000.0,13.500,175.56,2477

In [274]:
cars_new = cars.drop(['mileage', 'engine', 'max_power', 'torque', 'torque_rpm'], axis=1)

In [276]:
plt.figure(figsize=(8,8))
sns.heatmap(cars_new.corr(),annot=True,cmap='viridis',linewidths=.5)

ValueError: could not convert string to float: 'Maruti Swift Dzire VDI'

In [278]:
plt.figure(figsize=(8,8))
sns.heatmap(cars_new.corr(), annot=True, cmap='viridis', linewidths=0.5)

ValueError: could not convert string to float: 'Maruti Swift Dzire VDI'

In [280]:
cars_new.shape

(7906, 13)

In [282]:
cars_new.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,torque_nm,mileage_kmpl,max_power_bhp,engine_cc
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,5.0,190.00000,23.40,74.00,1248
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,5.0,250.00000,21.14,103.52,1498
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,5.0,12.70000,17.70,78.00,1497
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,5.0,219.66896,23.00,90.00,1396
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,5.0,11.50000,16.10,88.20,1298

In [350]:
# Now manage categorical data
cars_new['fuel'].value_counts()

fuel
 0    4299
 1    3520
-1      87
Name: count, dtype: int64

In [352]:
cars_new['seller_type'].value_counts()

seller_type
Individual          6563
Dealer              1107
Trustmark Dealer     236
Name: count, dtype: int64

In [354]:
cars_new['transmission'].value_counts()

transmission
Manual       6865
Automatic    1041
Name: count, dtype: int64

In [125]:
cars_new['owner'].value_counts()

owner
First Owner             5215
Second Owner            2016
Third Owner              510
Fourth & Above Owner     160
Test Drive Car             5
Name: count, dtype: int64

In [320]:
# def categorize_fuel(x):
#     if x == 'Petrol':
#         return '0'
#     elif x == 'Diesel':
#         return '1'
#     elif x == 'CNG':
#         return '2'
#     elif x == 'LPG':
#         return '3'

def ref3(x):
  if x == 'Petrol':
    return 1
  elif x == 'Diesel':
    return 0
  else:
    return -1

cars_new['fuel'] = cars_new['fuel'].map(ref3)

In [ ]:
def ref4(x):
  if x == 'Mannual':
    return 1
  elif x == 'Automatic':
    return 0
  

cars_new['transmission'] = cars_new['transmission'].map(ref3)

In [322]:
owners = pd.get_dummies(cars_new['owner'], dtype=int)

X = pd.concat([cars_new, owners], axis=1)

In [330]:
y = X['selling_price']
X = X.drop(['selling_price', 'name', 'owner'], axis = 1)

In [332]:
X.head()

,year,km_driven,fuel,seller_type,transmission,seats,torque_nm,mileage_kmpl,max_power_bhp,engine_cc,First Owner,Fourth & Above Owner,Second Owner,Test Drive Car,Third Owner
0,2014,145500,0,Individual,Manual,5.0,190.00000,23.40,74.00,1248,1,0,0,0,0
1,2014,120000,0,Individual,Manual,5.0,250.00000,21.14,103.52,1498,0,0,1,0,0
2,2006,140000,1,Individual,Manual,5.0,12.70000,17.70,78.00,1497,0,0,0,0,1
3,2010,127000,0,Individual,Manual,5.0,219.66896,23.00,90.00,1396,1,0,0,0,0
4,2007,120000,1,Individual,Manual,5.0,11.50000,16.10,88.20,1298,1,0,0,0,0

In [348]:
X.shape

(7906, 15)

In [334]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA

In [336]:
print(y.isnull().sum())

0

In [338]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X[:3000], y[:3000], test_size=0.2)

In [340]:
random_model = RandomForestRegressor(n_estimators=300, random_state = 42, n_jobs = -1)

In [346]:
print(Xtrain.isnull().sum())

year                    0
km_driven               0
fuel                    0
seller_type             0
transmission            0
seats                   0
torque_nm               0
mileage_kmpl            0
max_power_bhp           0
engine_cc               0
First Owner             0
Fourth & Above Owner    0
Second Owner            0
Test Drive Car          0
Third Owner             0
dtype: int64

In [344]:
#Fit
random_model.fit(Xtrain, ytrain)

y_pred = random_model.predict(Xtest)

#Checking the accuracy
random_model_accuracy = round(random_model.score(Xtrain, ytrain)*100,2)
print(round(random_model_accuracy, 2), '%')

ValueError: could not convert string to float: 'Individual'

In [310]:
#Fit
random_model.fit(Xtrain, ytrain)

y_pred = random_model.predict(Xtest)

#Checking the accuracy
random_model_accuracy = round(random_model.score(Xtrain, ytrain)*100,2)
print(round(random_model_accuracy, 2), '%')

ValueError: could not convert string to float: 'Diesel'

In [306]:
print(Xtrain.isnull().sum())

year                    0
km_driven               0
fuel                    0
seller_type             0
transmission            0
seats                   0
torque_nm               0
mileage_kmpl            0
max_power_bhp           0
engine_cc               0
First Owner             0
Fourth & Above Owner    0
Second Owner            0
Test Drive Car          0
Third Owner             0
dtype: int64

In [308]:
print(ytrain.isnull().sum())

0